[package]
name = "ed25519_tss_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
ed25519-dalek = "1"
curve25519-dalek = "3"
getrandom = { version = "0.2", features = ["js"] }
frost-ed25519 = { path = "../frost-main/frost-ed25519" }
postcard = "1"
rand = { version = "0.8", features = ["getrandom"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false


